/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vue;

import Contrôleur.*;
import Modele.Connexion;
import java.sql.SQLException;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author Arthur
 */
public class Accueil_Client extends javax.swing.JFrame {

    private Liste<Film> films;
    private final int y = 200;
    private Client User;

    private Connexion maconnexion;

    /**
     * Creates new form Accueil_Client
     */
    public Accueil_Client() {
        initComponents();
        films = new Liste<>();

        ArrayList<ArrayList<String>> ListBuffer = null;
        int compt = 0;

        try {
            maconnexion = new Connexion("projetpoojava", "root", "");

            ListBuffer = maconnexion.executeRequete("SELECT * FROM films;");

            // Creation de la liste d'objet de type films
            for (ArrayList<String> row : ListBuffer) {
                compt++;
                films.Ajouter(new Film(row, maconnexion));

                if (compt == 10) {
                    break;
                }
            }

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } catch (ClassNotFoundException e) {
            System.out.println(e.getMessage());
        }

        film1.setIcon(films.Get(0).getAffiche());
        film2.setIcon(films.Get(1).getAffiche());
        film3.setIcon(films.Get(2).getAffiche());
        film4.setIcon(films.Get(3).getAffiche());
        film5.setIcon(films.Get(4).getAffiche());
        film6.setIcon(films.Get(5).getAffiche());
        film7.setIcon(films.Get(6).getAffiche());
        film8.setIcon(films.Get(7).getAffiche());
        film9.setIcon(films.Get(8).getAffiche());
        film10.setIcon(films.Get(9).getAffiche());

        User = new Client();
    }

    javax.swing.JFrame test;

    public Accueil_Client(Client theUser) {
        initComponents();
        films = new Liste<>();

        ArrayList<ArrayList<String>> ListBuffer = null;
        int compt = 0;

        try {
            maconnexion = new Connexion("projetpoojava", "root", "");

            ListBuffer = maconnexion.executeRequete("SELECT * FROM films;");

            // Creation de la liste d'objet de type films
            for (ArrayList<String> row : ListBuffer) {
                compt++;
                films.Ajouter(new Film(row, maconnexion));

                if (compt == 10) {
                    break;
                }
            }

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } catch (ClassNotFoundException e) {
            System.out.println(e.getMessage());
        }

        film1.setIcon(films.Get(0).getAffiche());
        film2.setIcon(films.Get(1).getAffiche());
        film3.setIcon(films.Get(2).getAffiche());
        film4.setIcon(films.Get(3).getAffiche());
        film5.setIcon(films.Get(4).getAffiche());
        film6.setIcon(films.Get(5).getAffiche());
        film7.setIcon(films.Get(6).getAffiche());
        film8.setIcon(films.Get(7).getAffiche());
        film9.setIcon(films.Get(8).getAffiche());
        film10.setIcon(films.Get(9).getAffiche());

        User = new Client(theUser);

        if ((User.getPrenom() == "NoAccountUser") && (User.getNom() == "") && (User.getEmail() == "noMail") && (User.getPassword() == "noPassword")) {
            jComboBox1.removeAllItems();
            jComboBox1.addItem("Se déconnecter");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jButtonFilm = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButtonActeur = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButtonRealisateur = new javax.swing.JButton();
        jScrollBar1 = new javax.swing.JScrollBar();
        film1 = new javax.swing.JLabel();
        film2 = new javax.swing.JLabel();
        film3 = new javax.swing.JLabel();
        film4 = new javax.swing.JLabel();
        film5 = new javax.swing.JLabel();
        film6 = new javax.swing.JLabel();
        film7 = new javax.swing.JLabel();
        film8 = new javax.swing.JLabel();
        film9 = new javax.swing.JLabel();
        film10 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("Bienvenue sur MY POPCORN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 620, 73);

        jButtonFilm.setText("Voir les films");
        jButtonFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFilmActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFilm);
        jButtonFilm.setBounds(0, 120, 225, 25);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mon compte", "Voir mon profil", "Mes films ", "Prochaines séances", "Se déconnecter" }));
        jComboBox1.setToolTipText("");
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(660, 50, 220, 22);

        jButtonActeur.setText("Voir les acteurs");
        jButtonActeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActeurActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonActeur);
        jButtonActeur.setBounds(220, 120, 225, 25);

        jButton2.setText("Accueil");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(660, 120, 225, 25);

        jButtonRealisateur.setText("Voir les réalisateurs");
        jButtonRealisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRealisateurActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRealisateur);
        jButtonRealisateur.setBounds(440, 120, 225, 25);

        jScrollBar1.setMaximum(26);
        jScrollBar1.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        jScrollBar1.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                jScrollBar1AdjustmentValueChanged(evt);
            }
        });
        getContentPane().add(jScrollBar1);
        jScrollBar1.setBounds(10, 500, 875, 17);

        film1.setText("jLabel2");
        film1.setBorder(new javax.swing.border.MatteBorder(null));
        film1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                film1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                film1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                film1MouseExited(evt);
            }
        });
        getContentPane().add(film1);
        film1.setBounds(30, 200, 200, 290);

        film2.setText("jLabel2");
        film2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                film2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                film2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                film2MouseExited(evt);
            }
        });
        getContentPane().add(film2);
        film2.setBounds(280, 200, 200, 290);

        film3.setText("jLabel2");
        film3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                film3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                film3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                film3MouseExited(evt);
            }
        });
        getContentPane().add(film3);
        film3.setBounds(530, 200, 200, 290);

        film4.setText("jLabel2");
        film4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                film4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                film4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                film4MouseExited(evt);
            }
        });
        getContentPane().add(film4);
        film4.setBounds(780, 200, 200, 290);

        film5.setText("jLabel2");
        film5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                film5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                film5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                film5MouseExited(evt);
            }
        });
        getContentPane().add(film5);
        film5.setBounds(1030, 200, 200, 290);

        film6.setText("jLabel2");
        film6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                film6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                film6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                film6MouseExited(evt);
            }
        });
        getContentPane().add(film6);
        film6.setBounds(1280, 200, 200, 290);

        film7.setText("jLabel2");
        film7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                film7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                film7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                film7MouseExited(evt);
            }
        });
        getContentPane().add(film7);
        film7.setBounds(1530, 200, 200, 290);

        film8.setText("jLabel2");
        film8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                film8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                film8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                film8MouseExited(evt);
            }
        });
        getContentPane().add(film8);
        film8.setBounds(1780, 200, 200, 290);

        film9.setText("jLabel2");
        film9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                film9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                film9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                film9MouseExited(evt);
            }
        });
        getContentPane().add(film9);
        film9.setBounds(2030, 200, 200, 290);

        film10.setText("jLabel2");
        film10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                film10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                film10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                film10MouseExited(evt);
            }
        });
        getContentPane().add(film10);
        film10.setBounds(2280, 200, 200, 290);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFilmActionPerformed

        TousLesFilms window1 = new TousLesFilms(0, User);
        window1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonFilmActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Accueil_Client window = new Accueil_Client(User);
        window.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jScrollBar1AdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_jScrollBar1AdjustmentValueChanged
        film1.setLocation(30 - jScrollBar1.getValue() * 100, y);
        film2.setLocation(280 - jScrollBar1.getValue() * 100, y);
        film3.setLocation(530 - jScrollBar1.getValue() * 100, y);
        film4.setLocation(780 - jScrollBar1.getValue() * 100, y);
        film5.setLocation(1030 - jScrollBar1.getValue() * 100, y);
        film6.setLocation(1280 - jScrollBar1.getValue() * 100, y);
        film7.setLocation(1530 - jScrollBar1.getValue() * 100, y);
        film8.setLocation(1780 - jScrollBar1.getValue() * 100, y);
        film9.setLocation(2030 - jScrollBar1.getValue() * 100, y);
        film10.setLocation(2280 - jScrollBar1.getValue() * 100, y);
    }//GEN-LAST:event_jScrollBar1AdjustmentValueChanged

    private void film1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film1MouseClicked
        Film_Infos infos = new Film_Infos(films.Get(0), User);
        infos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_film1MouseClicked

    private void film1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film1MouseEntered
        film1.setBorder(BorderFactory.createLoweredBevelBorder());
    }//GEN-LAST:event_film1MouseEntered

    private void film1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film1MouseExited
        film1.setBorder(BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_film1MouseExited

    private void film2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film2MouseEntered
        film2.setBorder(BorderFactory.createLoweredBevelBorder());
    }//GEN-LAST:event_film2MouseEntered

    private void film2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film2MouseExited
        film2.setBorder(BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_film2MouseExited

    private void film3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film3MouseEntered
        film3.setBorder(BorderFactory.createLoweredBevelBorder());
    }//GEN-LAST:event_film3MouseEntered

    private void film3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film3MouseExited
        film3.setBorder(BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_film3MouseExited

    private void film4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film4MouseEntered
        film4.setBorder(BorderFactory.createLoweredBevelBorder());
    }//GEN-LAST:event_film4MouseEntered

    private void film4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film4MouseExited
        film4.setBorder(BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_film4MouseExited

    private void film5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film5MouseEntered
        film5.setBorder(BorderFactory.createLoweredBevelBorder());
    }//GEN-LAST:event_film5MouseEntered

    private void film5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film5MouseExited
        film5.setBorder(BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_film5MouseExited

    private void film6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film6MouseEntered
        film6.setBorder(BorderFactory.createLoweredBevelBorder());
    }//GEN-LAST:event_film6MouseEntered

    private void film6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film6MouseExited
        film6.setBorder(BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_film6MouseExited

    private void film7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film7MouseEntered
        film7.setBorder(BorderFactory.createLoweredBevelBorder());
    }//GEN-LAST:event_film7MouseEntered

    private void film7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film7MouseExited
        film7.setBorder(BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_film7MouseExited

    private void film8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film8MouseEntered
        film8.setBorder(BorderFactory.createLoweredBevelBorder());
    }//GEN-LAST:event_film8MouseEntered

    private void film8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film8MouseExited
        film8.setBorder(BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_film8MouseExited

    private void film9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film9MouseEntered
        film9.setBorder(BorderFactory.createLoweredBevelBorder());
    }//GEN-LAST:event_film9MouseEntered

    private void film9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film9MouseExited
        film9.setBorder(BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_film9MouseExited

    private void film10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film10MouseEntered
        film10.setBorder(BorderFactory.createLoweredBevelBorder());
    }//GEN-LAST:event_film10MouseEntered

    private void film10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film10MouseExited
        film10.setBorder(BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_film10MouseExited

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if (jComboBox1.getSelectedIndex() != 0) {
            switch (jComboBox1.getSelectedIndex()) 
            {   

                case 1: // voir mon profil
                   
                        Profil window = new Profil(User);
                        window.setVisible(true);
                        this.dispose();

                    break;
                case 2: // voir mes films
                    VoirMesFilms window2 = new VoirMesFilms(User);
                    window2.setVisible(true);
                    this.dispose();
                    break;
                case 3: // voir mes scéances
                   // MesSeances window3 = new MesSeances();
                   // window3.setVisible(true);
                   // this.dispose();
                    break;

                case 4: // deconnexion

                    Identification theWindow3 = new Identification();
                    theWindow3.setVisible(true);

                    this.dispose();
                    break;

                default:
                    break;
            }
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButtonActeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActeurActionPerformed
        TousLesFilms filo = new TousLesFilms(1, User);
        filo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonActeurActionPerformed

    private void jButtonRealisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRealisateurActionPerformed
        TousLesFilms filo = new TousLesFilms(2, User);
        filo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonRealisateurActionPerformed

    private void film2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film2MouseClicked
        Film_Infos infos = new Film_Infos(films.Get(1), User);
        infos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_film2MouseClicked

    private void film3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film3MouseClicked
        Film_Infos infos = new Film_Infos(films.Get(2), User);
        infos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_film3MouseClicked

    private void film4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film4MouseClicked
        Film_Infos infos = new Film_Infos(films.Get(3), User);
        infos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_film4MouseClicked

    private void film5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film5MouseClicked
        Film_Infos infos = new Film_Infos(films.Get(4), User);
        infos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_film5MouseClicked

    private void film6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film6MouseClicked
        Film_Infos infos = new Film_Infos(films.Get(5), User);
        infos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_film6MouseClicked

    private void film7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film7MouseClicked
        Film_Infos infos = new Film_Infos(films.Get(6), User);
        infos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_film7MouseClicked

    private void film8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film8MouseClicked
        Film_Infos infos = new Film_Infos(films.Get(7), User);
        infos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_film8MouseClicked

    private void film9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film9MouseClicked
        Film_Infos infos = new Film_Infos(films.Get(8), User);
        infos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_film9MouseClicked

    private void film10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film10MouseClicked
        Film_Infos infos = new Film_Infos(films.Get(9), User);
        infos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_film10MouseClicked

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked

        if ((User.getPrenom() == "NoAccountUser") && (User.getNom() == "") && (User.getEmail() == "noMail") && (User.getPassword() == "noPassword")) {
            Identification theWindow3 = new Identification();
            theWindow3.setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_jComboBox1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accueil_Client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel film1;
    private javax.swing.JLabel film10;
    private javax.swing.JLabel film2;
    private javax.swing.JLabel film3;
    private javax.swing.JLabel film4;
    private javax.swing.JLabel film5;
    private javax.swing.JLabel film6;
    private javax.swing.JLabel film7;
    private javax.swing.JLabel film8;
    private javax.swing.JLabel film9;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonActeur;
    private javax.swing.JButton jButtonFilm;
    private javax.swing.JButton jButtonRealisateur;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollBar jScrollBar1;
    // End of variables declaration//GEN-END:variables
}
