/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Contrôleur.*;
import Modele.Connexion;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.BorderFactory;

/**
 *
 * @author Amna9
 */
public class Accueil_Employe extends javax.swing.JFrame {

    private Liste<Film> films;
    private final int y = 200;
    private Administrateur User;

    private Connexion maconnexion;

    /**
     * Creates new form Accueil_Employe
     */
    public Accueil_Employe() {
        initComponents();
        films = new Liste<>();
        
         //Init size
        this.setSize(new Dimension(900, 700));

        ArrayList<ArrayList<String>> ListBuffer = null;
        int compt = 0;

        try {
            maconnexion = new Connexion("projetpoojava", "root", "");

            ListBuffer = maconnexion.executeRequete("SELECT * FROM films;");

            // Creation de la liste d'objet de type films
            for (ArrayList<String> row : ListBuffer) {
                compt++;
                films.Ajouter(new Film(row, maconnexion));

                if (compt == 10) {
                    break;
                }
            }

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } catch (ClassNotFoundException e) {
            System.out.println(e.getMessage());
        }

        film1.setIcon(films.Get(0).getAffiche());
        film2.setIcon(films.Get(1).getAffiche());
        film3.setIcon(films.Get(2).getAffiche());
        film4.setIcon(films.Get(3).getAffiche());
        film5.setIcon(films.Get(4).getAffiche());
        film6.setIcon(films.Get(5).getAffiche());
        film7.setIcon(films.Get(6).getAffiche());
        film8.setIcon(films.Get(7).getAffiche());
        film9.setIcon(films.Get(8).getAffiche());
        film10.setIcon(films.Get(9).getAffiche());

        User = new Administrateur();
    }

    public Accueil_Employe(Utilisateur theUser) {
        initComponents();
        films = new Liste<>();
       
        ArrayList<ArrayList<String>> ListBuffer = null;
        int compt = 0;

        try {
            maconnexion = new Connexion("projetpoojava", "root", "");

            ListBuffer = maconnexion.executeRequete("SELECT * FROM films;");

            // Creation de la liste d'objet de type films
            for (ArrayList<String> row : ListBuffer) {
                compt++;
                films.Ajouter(new Film(row, maconnexion));

                if (compt == 10) {
                    break;
                }
            }

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } catch (ClassNotFoundException e) {
            System.out.println(e.getMessage());
        }

        film1.setIcon(films.Get(0).getAffiche());
        film2.setIcon(films.Get(1).getAffiche());
        film3.setIcon(films.Get(2).getAffiche());
        film4.setIcon(films.Get(3).getAffiche());
        film5.setIcon(films.Get(4).getAffiche());
        film6.setIcon(films.Get(5).getAffiche());
        film7.setIcon(films.Get(6).getAffiche());
        film8.setIcon(films.Get(7).getAffiche());
        film9.setIcon(films.Get(8).getAffiche());
        film10.setIcon(films.Get(9).getAffiche());
     

       
        User = new Administrateur(theUser);
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Accueil = new javax.swing.JButton();
        Films = new javax.swing.JButton();
        Dossiers = new javax.swing.JButton();
        Offres = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollBar1 = new javax.swing.JScrollBar();
        film1 = new javax.swing.JLabel();
        film2 = new javax.swing.JLabel();
        film3 = new javax.swing.JLabel();
        film4 = new javax.swing.JLabel();
        film5 = new javax.swing.JLabel();
        film6 = new javax.swing.JLabel();
        film7 = new javax.swing.JLabel();
        film8 = new javax.swing.JLabel();
        film9 = new javax.swing.JLabel();
        film10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LalaLand");
        setBackground(new java.awt.Color(153, 255, 153));
        setPreferredSize(new java.awt.Dimension(645, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(645, 600));
        getContentPane().setLayout(null);

        Accueil.setBackground(new java.awt.Color(253, 0, 0));
        Accueil.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        Accueil.setText("Accueil");
        Accueil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccueilMouseClicked(evt);
            }
        });
        Accueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccueilActionPerformed(evt);
            }
        });
        getContentPane().add(Accueil);
        Accueil.setBounds(0, 62, 154, 41);

        Films.setBackground(new java.awt.Color(253, 0, 0));
        Films.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        Films.setText("Films");
        Films.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilmsActionPerformed(evt);
            }
        });
        getContentPane().add(Films);
        Films.setBounds(164, 62, 154, 41);

        Dossiers.setBackground(new java.awt.Color(253, 0, 0));
        Dossiers.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        Dossiers.setText("Acteurs");
        Dossiers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DossiersActionPerformed(evt);
            }
        });
        getContentPane().add(Dossiers);
        Dossiers.setBounds(328, 62, 154, 41);

        Offres.setBackground(new java.awt.Color(253, 0, 0));
        Offres.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        Offres.setText("Offres");
        Offres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OffresActionPerformed(evt);
            }
        });
        getContentPane().add(Offres);
        Offres.setBounds(492, 62, 154, 40);

        jLabel5.setBackground(new java.awt.Color(255, 51, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel5.setText("                                  MY POPCORN");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 416, 50);

        jButton1.setText("Se déconnecter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(507, 0, 139, 29);

        jScrollBar1.setMaximum(26);
        jScrollBar1.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        jScrollBar1.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                jScrollBar1AdjustmentValueChanged(evt);
            }
        });
        getContentPane().add(jScrollBar1);
        jScrollBar1.setBounds(10, 500, 620, 26);

        film1.setText("jLabel2");
        film1.setBorder(new javax.swing.border.MatteBorder(null));
        film1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                film1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                film1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                film1MouseExited(evt);
            }
        });
        getContentPane().add(film1);
        film1.setBounds(30, 200, 200, 290);

        film2.setText("jLabel2");
        film2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                film2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                film2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                film2MouseExited(evt);
            }
        });
        getContentPane().add(film2);
        film2.setBounds(280, 200, 200, 290);

        film3.setText("jLabel2");
        film3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                film3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                film3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                film3MouseExited(evt);
            }
        });
        getContentPane().add(film3);
        film3.setBounds(530, 200, 200, 290);

        film4.setText("jLabel2");
        film4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                film4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                film4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                film4MouseExited(evt);
            }
        });
        getContentPane().add(film4);
        film4.setBounds(780, 200, 200, 290);

        film5.setText("jLabel2");
        film5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                film5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                film5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                film5MouseExited(evt);
            }
        });
        getContentPane().add(film5);
        film5.setBounds(1030, 200, 200, 290);

        film6.setText("jLabel2");
        film6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                film6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                film6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                film6MouseExited(evt);
            }
        });
        getContentPane().add(film6);
        film6.setBounds(1280, 200, 200, 290);

        film7.setText("jLabel2");
        film7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                film7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                film7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                film7MouseExited(evt);
            }
        });
        getContentPane().add(film7);
        film7.setBounds(1530, 200, 200, 290);

        film8.setText("jLabel2");
        film8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                film8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                film8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                film8MouseExited(evt);
            }
        });
        getContentPane().add(film8);
        film8.setBounds(1780, 200, 200, 290);

        film9.setText("jLabel2");
        film9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                film9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                film9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                film9MouseExited(evt);
            }
        });
        getContentPane().add(film9);
        film9.setBounds(2030, 200, 200, 290);

        film10.setText("jLabel2");
        film10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                film10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                film10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                film10MouseExited(evt);
            }
        });
        getContentPane().add(film10);
        film10.setBounds(2280, 200, 200, 290);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AccueilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccueilActionPerformed
    Accueil_Employe g = new Accueil_Employe();
    g.setVisible(true);  
    this.setVisible(false);
    }//GEN-LAST:event_AccueilActionPerformed

    private void OffresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OffresActionPerformed
    Offres g = new Offres();
    g.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_OffresActionPerformed

    private void DossiersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DossiersActionPerformed
    Films g = new Films();
    g.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_DossiersActionPerformed

    private void FilmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilmsActionPerformed
    Films g = new Films();
    g.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_FilmsActionPerformed

    private void AccueilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccueilMouseClicked
   
    
    }//GEN-LAST:event_AccueilMouseClicked

    private void jScrollBar1AdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_jScrollBar1AdjustmentValueChanged
        film1.setLocation(30 - jScrollBar1.getValue() * 100, y);
        film2.setLocation(280 - jScrollBar1.getValue() * 100, y);
        film3.setLocation(530 - jScrollBar1.getValue() * 100, y);
        film4.setLocation(780 - jScrollBar1.getValue() * 100, y);
        film5.setLocation(1030 - jScrollBar1.getValue() * 100, y);
        film6.setLocation(1280 - jScrollBar1.getValue() * 100, y);
        film7.setLocation(1530 - jScrollBar1.getValue() * 100, y);
        film8.setLocation(1780 - jScrollBar1.getValue() * 100, y);
        film9.setLocation(2030 - jScrollBar1.getValue() * 100, y);
        film10.setLocation(2280 - jScrollBar1.getValue() * 100, y);
    }//GEN-LAST:event_jScrollBar1AdjustmentValueChanged

    private void film1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film1MouseClicked
        Ajout_Film infos = new Ajout_Film(films.Get(0));
        infos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_film1MouseClicked

    private void film1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film1MouseEntered
        film1.setBorder(BorderFactory.createLoweredBevelBorder());
    }//GEN-LAST:event_film1MouseEntered

    private void film1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film1MouseExited
        film1.setBorder(BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_film1MouseExited

    private void film2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film2MouseClicked
        Ajout_Film infos = new Ajout_Film(films.Get(1));
        infos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_film2MouseClicked

    private void film2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film2MouseEntered
        film2.setBorder(BorderFactory.createLoweredBevelBorder());
    }//GEN-LAST:event_film2MouseEntered

    private void film2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film2MouseExited
        film2.setBorder(BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_film2MouseExited

    private void film3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film3MouseClicked
        Ajout_Film infos = new Ajout_Film(films.Get(2));
        infos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_film3MouseClicked

    private void film3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film3MouseEntered
        film3.setBorder(BorderFactory.createLoweredBevelBorder());
    }//GEN-LAST:event_film3MouseEntered

    private void film3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film3MouseExited
        film3.setBorder(BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_film3MouseExited

    private void film4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film4MouseClicked
        Ajout_Film infos = new Ajout_Film(films.Get(3));
        infos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_film4MouseClicked

    private void film4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film4MouseEntered
        film4.setBorder(BorderFactory.createLoweredBevelBorder());
    }//GEN-LAST:event_film4MouseEntered

    private void film4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film4MouseExited
        film4.setBorder(BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_film4MouseExited

    private void film5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film5MouseClicked
        Ajout_Film infos = new Ajout_Film(films.Get(4));
        infos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_film5MouseClicked

    private void film5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film5MouseEntered
        film5.setBorder(BorderFactory.createLoweredBevelBorder());
    }//GEN-LAST:event_film5MouseEntered

    private void film5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film5MouseExited
        film5.setBorder(BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_film5MouseExited

    private void film6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film6MouseClicked
        Ajout_Film infos = new Ajout_Film(films.Get(5));
        infos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_film6MouseClicked

    private void film6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film6MouseEntered
        film6.setBorder(BorderFactory.createLoweredBevelBorder());
    }//GEN-LAST:event_film6MouseEntered

    private void film6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film6MouseExited
        film6.setBorder(BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_film6MouseExited

    private void film7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film7MouseClicked
        Ajout_Film infos = new Ajout_Film(films.Get(6));
        infos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_film7MouseClicked

    private void film7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film7MouseEntered
        film7.setBorder(BorderFactory.createLoweredBevelBorder());
    }//GEN-LAST:event_film7MouseEntered

    private void film7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film7MouseExited
        film7.setBorder(BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_film7MouseExited

    private void film8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film8MouseClicked
        Ajout_Film infos = new Ajout_Film(films.Get(7));
        infos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_film8MouseClicked

    private void film8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film8MouseEntered
        film8.setBorder(BorderFactory.createLoweredBevelBorder());
    }//GEN-LAST:event_film8MouseEntered

    private void film8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film8MouseExited
        film8.setBorder(BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_film8MouseExited

    private void film9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film9MouseClicked
        Ajout_Film infos = new Ajout_Film(films.Get(8));
        infos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_film9MouseClicked

    private void film9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film9MouseEntered
        film9.setBorder(BorderFactory.createLoweredBevelBorder());
    }//GEN-LAST:event_film9MouseEntered

    private void film9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film9MouseExited
        film9.setBorder(BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_film9MouseExited

    private void film10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film10MouseClicked
        Ajout_Film infos = new Ajout_Film(films.Get(9));
        infos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_film10MouseClicked

    private void film10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film10MouseEntered
        film10.setBorder(BorderFactory.createLoweredBevelBorder());
    }//GEN-LAST:event_film10MouseEntered

    private void film10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_film10MouseExited
        film10.setBorder(BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_film10MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Identification window = new Identification();
window.setVisible(true);
this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil_Employe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil_Employe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil_Employe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil_Employe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accueil_Employe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Accueil;
    private javax.swing.JButton Dossiers;
    private javax.swing.JButton Films;
    private javax.swing.JButton Offres;
    private javax.swing.JLabel film1;
    private javax.swing.JLabel film10;
    private javax.swing.JLabel film2;
    private javax.swing.JLabel film3;
    private javax.swing.JLabel film4;
    private javax.swing.JLabel film5;
    private javax.swing.JLabel film6;
    private javax.swing.JLabel film7;
    private javax.swing.JLabel film8;
    private javax.swing.JLabel film9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollBar jScrollBar1;
    // End of variables declaration//GEN-END:variables
}
