/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vue;

import javax.swing.*;
import Contrôleur.*;
import Modele.Connexion;
import java.awt.Component;
import java.awt.Dimension;
import java.io.File;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Arrays;

/**
 * Fenêtre permettant d'ajouter un film à la bdd
 * @author Arthur
 */
public class Ajout_Film extends javax.swing.JFrame {

    private Connexion maconnexion;
    private boolean modif;
    private Film monfilm;
    private int salle;
    //private Administrateur admin;

    /**
     * Creates new form Ajout_Film
     */
    public Ajout_Film() {
        initComponents();
        
         //Init size
        this.setSize(new Dimension(900, 700));
        jButton7.setVisible(false);
        try {
            maconnexion = new Connexion("projetpoojava", "root", "");
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } catch (ClassNotFoundException e) {
            System.out.println(e.getMessage());
        }
        modif = false;

        try {
            salle = Integer.parseInt(maconnexion.executeRequete("SELECT MAX(salle) FROM films;").get(0).get(0)) + 1;
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }

    }

    public Ajout_Film(Film movie) {
        initComponents();
        jTextField1.setText(movie.getNom());
        jSpinner3.setValue(movie.getDate().get(movie.getDate().DATE));
        jSpinner2.setValue(movie.getDate().get(movie.getDate().MONTH) + 1);
        jSpinner1.setValue(movie.getDate().get(movie.getDate().YEAR));
        jTextField3.setText(movie.getPays());
        jTextField4.setText(movie.getDuree() + "");
        jTextField5.setText(movie.getGenre());
        jTextArea1.setText(movie.getDescription());
        affiche.setIcon(movie.getAffiche());
        boutton.setVisible(false);
        jButton7.setVisible(false);

        jList1.setModel(movie.getRealisateur().getModele());
        jList2.setModel(movie.getActeurs().getModele());

        try {
            maconnexion = new Connexion("projetpoojava", "root", "");
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } catch (ClassNotFoundException e) {
            System.out.println(e.getMessage());
        }
        modif = true;
        monfilm = movie;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boutton = new javax.swing.JButton();
        affiche = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jSpinner3 = new javax.swing.JSpinner();
        jTextField5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(null);

        boutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boutton.setText("Ajouter une affiche");
        boutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouttonActionPerformed(evt);
            }
        });
        getContentPane().add(boutton);
        boutton.setBounds(20, 170, 200, 31);
        getContentPane().add(affiche);
        affiche.setBounds(20, 40, 200, 290);

        jTextField1.setText("Titre du film");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(240, 30, 590, 50);

        jTextField3.setText("Pays");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(560, 100, 190, 22);

        jTextField4.setText("Durée");
        getContentPane().add(jTextField4);
        jTextField4.setBounds(760, 100, 70, 22);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Description");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(240, 150, 590, 140);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(780, 480, 49, 25);

        jButton2.setText("Annuler");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(240, 480, 73, 25);

        jScrollPane2.setViewportView(jList1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(240, 300, 590, 80);

        jScrollPane3.setViewportView(jList2);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(240, 390, 590, 80);

        jButton3.setText("+");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(830, 300, 50, 25);

        jButton4.setText("-");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(830, 350, 50, 25);

        jButton5.setText("+");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(830, 390, 50, 25);

        jButton6.setText("-");
        getContentPane().add(jButton6);
        jButton6.setBounds(830, 440, 50, 25);

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton7.setText("Modifier l'affiche");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(20, 330, 200, 31);
        getContentPane().add(jSpinner1);
        jSpinner1.setBounds(480, 100, 70, 22);
        getContentPane().add(jSpinner2);
        jSpinner2.setBounds(420, 100, 50, 22);
        getContentPane().add(jSpinner3);
        jSpinner3.setBounds(362, 100, 50, 22);

        jTextField5.setText("Genre");
        getContentPane().add(jTextField5);
        jTextField5.setBounds(240, 100, 110, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bouttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouttonActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        try {
            affiche.setIcon(new ImageIcon(chooser.getSelectedFile().toString()));
            boutton.setVisible(false);
            jButton7.setVisible(true);
            chooser.getSelectedFile().renameTo(new File(new File("/images/Films/"), chooser.getSelectedFile().getName()));
        } catch (Exception e) {
            boutton.setVisible(true);
            jButton7.setVisible(false);
        }
    }//GEN-LAST:event_bouttonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Films window = new Films();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Ajout dans la base de données
        DecimalFormat df = new DecimalFormat("00");
        DecimalFormat df2 = new DecimalFormat("0000");


        try {
        if (modif) {
            maconnexion.executeUpdate("UPDATE films SET titre='" + jTextField1.getText() + "', genre='" + jTextField5.getText() + "', durée='" + jTextField4.getText() + "', description='" + jTextArea1.getText().replace("'", " ") + "', Pays='" + jTextField3.getText() + "', date='" + df.format(jSpinner2.getValue()) + "/" + df.format(jSpinner3.getValue()) + "/" + df2.format(jSpinner1.getValue()) + "' WHERE IDfilm='" + monfilm.getID() + "';");
            
        } else {
            maconnexion.executeUpdate("INSERT INTO films (titre,genre,durée,note,description,pays,date,salle,IDfilm) VALUES ('" + jTextField1.getText() + "','" + jTextField5.getText() + "','" + jTextField4.getText() + "','" + 0 + "','" + jTextArea1.getText() + "','" + jTextField3.getText() + "','" + df.format(jSpinner2.getValue()) + "/" + df.format(jSpinner3.getValue()) + "/" + df2.format(jSpinner1.getValue()) + "','" + salle + "','F000" + salle + "');");
            
        }
        //Ajoute les réalisateurs dans la base, tout en vérifiant qu'ils n'y sont pas déjà insérés
        for(int i=0;i<monfilm.getRealisateur().Taille();i++) {
            String prenom="", nom="";
            int j=0;
            while (monfilm.getRealisateur().Get(i).charAt(j)!=' '){
                prenom+=monfilm.getRealisateur().Get(i).charAt(j);
                j++;
            }
            for(int k=j+1;k<monfilm.getRealisateur().Get(i).length();k++) {
                nom+=monfilm.getRealisateur().Get(i).charAt(k);
            }
            String pid = maconnexion.executeRequete("SELECT IDpersonne FROM personne WHERE prenom='" + prenom.trim() + "' AND nom='" + nom.trim() + "';").get(0).get(0);

            if(maconnexion.executeRequete("SELECT * FROM relationfilmpersonne WHERE IDfilm='" + monfilm.getID() + "' AND MetierLien='realisateur' AND IDpersonne='" + pid + "';").isEmpty())
                maconnexion.executeUpdate("INSERT INTO relationfilmpersonne (IDfilm,MetierLien,IDpersonne) VALUES ('" + monfilm.getID() + "','realisateur','" + pid + "');");
        }
        //Ajoute les acteurs dans la base, tout en vérifiant qu'ils n'y sont pas déjà insérés
        for(int i=0;i<monfilm.getActeurs().Taille();i++) {
            String prenom="", nom="";
            int j=0;
            while (monfilm.getActeurs().Get(i).charAt(j)!=' '){
                prenom+=monfilm.getActeurs().Get(i).charAt(j);
                j++;
            }
            for(int k=j+1;j<monfilm.getActeurs().Get(i).length();k++) {
                nom+=monfilm.getActeurs().Get(i).charAt(j);
            }
            String pid = maconnexion.executeRequete("SELECT IDpersonne FROM personne WHERE prenom='" + prenom + "' AND nom='" + nom + "';").get(0).get(0);
            if(maconnexion.executeRequete("SELECT * FROM relationfilmpersonne WHERE IDfilm='" + monfilm.getID() + "' AND MetierLien='acteur' AND IDpersonne='" + pid + "';").isEmpty())
                maconnexion.executeUpdate("INSERT INTO relationfilmpersonne (IDfilm,MetierLien,IDpersonne) VALUES ('" + monfilm.getID() + "','acteur'," + pid + "');");
        }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        Films window = new Films();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        JFileChooser chooser = new JFileChooser("../images/Films/..");
        Icon last = affiche.getIcon();
        chooser.showOpenDialog(null);
        try {
            affiche.setIcon(new ImageIcon(chooser.getSelectedFile().toString()));
            //chooser.getSelectedFile().renameTo(new File(new File("/images/Films/"),chooser.getSelectedFile().toString()));
        } catch (Exception e) {
            affiche.setIcon(last);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Choisir_actreal window = new Choisir_actreal(this, MetierDuCinema.realisateur);
        window.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Choisir_actreal window = new Choisir_actreal(this, MetierDuCinema.acteur);
        window.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    public Film getFilm() {
        return monfilm;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ajout_Film.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ajout_Film.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ajout_Film.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ajout_Film.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ajout_Film().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel affiche;
    private javax.swing.JButton boutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
