/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vue;

import javax.swing.*;
import Contrôleur.*;
import Modele.*;
import java.awt.Dimension;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Fenêtre permettant d'ajouter des artistes à la bdd
 * @author Arthur, Kevin, Lucas, Amna
 */
public class Ajout_ActReal extends javax.swing.JFrame {

private boolean modif;
private Connexion maconnexion;
private Personne mapersonne;
private String id;

    /**
     * Creates new form Ajout_ActReal
     */
    public Ajout_ActReal() {
        initComponents();
    jTextField1.setText("Prénom de l'artiste");
    jTextField5.setText("Nom de l'artiste");
     //Init size
        this.setSize(new Dimension(900, 700));
modif=false;
        try {
            maconnexion = new Connexion("projetpoojava", "root", "");
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } catch (ClassNotFoundException e) {
            System.out.println(e.getMessage());
        }
        try {
            id = "P" + Integer.parseInt(maconnexion.executeRequete("SELECT MAX(IDpersonne) FROM personne;").get(0).get(0).substring(1));
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
}

    

public Ajout_ActReal(Personne pers) {
initComponents();

jTextField1.setText(pers.getPrenom());
jTextField5.setText(pers.getNom());
jSpinner1.setValue(pers.getDateCalendar().get(pers.getDateCalendar().DATE));
jSpinner2.setValue(pers.getDateCalendar().get(pers.getDateCalendar().MONTH)+1);
jSpinner3.setValue(pers.getDateCalendar().get(pers.getDateCalendar().YEAR));
modif=true;
        try {
            maconnexion = new Connexion("projetpoojava", "root", "");
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } catch (ClassNotFoundException e) {
            System.out.println(e.getMessage());
        }
affiche.setIcon(pers.getPhoto());
if(pers.getMetier().equals(MetierDuCinema.acteur)) {
jRadioButton1.setSelected(true);
}
if(pers.getMetier().equals(MetierDuCinema.realisateur)) {
jRadioButton1.setSelected(true);
}
boutton.setVisible(false);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boutton = new javax.swing.JButton();
        affiche = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jSpinner3 = new javax.swing.JSpinner();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(null);

        boutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boutton.setText("Ajouter une photo");
        boutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouttonActionPerformed(evt);
            }
        });
        getContentPane().add(boutton);
        boutton.setBounds(10, 220, 200, 31);
        getContentPane().add(affiche);
        affiche.setBounds(10, 90, 200, 290);

        jTextField5.setText("Nom du actreal");
        jTextField5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField5MouseClicked(evt);
            }
        });
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(560, 120, 270, 50);

        jTextField1.setText("Prénom du actreal");
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(240, 120, 270, 50);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(770, 440, 53, 29);

        jButton2.setText("Annuler");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(230, 440, 89, 29);
        getContentPane().add(jSpinner1);
        jSpinner1.setBounds(240, 210, 80, 26);
        getContentPane().add(jSpinner2);
        jSpinner2.setBounds(340, 210, 80, 26);
        getContentPane().add(jSpinner3);
        jSpinner3.setBounds(440, 210, 120, 26);

        jRadioButton1.setText("Acteur");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(240, 280, 79, 29);

        jRadioButton2.setText("Réalisateur");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(240, 320, 109, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bouttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouttonActionPerformed
        
Icon last = affiche.getIcon();
try {
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        affiche.setIcon(new ImageIcon(chooser.getSelectedFile().toString()));
} catch (Exception e) {
affiche.setIcon(last);
}
    }//GEN-LAST:event_bouttonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Ajout dans la base de données
        DecimalFormat df = new DecimalFormat("00");
        DecimalFormat df2 = new DecimalFormat("0000");
        try {
        if (modif) {
            maconnexion.executeUpdate("UPDATE personne SET prenom='" + jTextField1.getText() + "', nom='" + jTextField5.getText() + "', DateNaissance='" + df.format(jSpinner2.getValue()) + "/" + df.format(jSpinner1.getValue()) + "/" + df2.format(jSpinner3.getValue()) + "' WHERE IDpersonne='" + id + "';");
            
        } else {
            maconnexion.executeUpdate("INSERT INTO personne (prenom,nom,IDPersonne,DateNaissance) VALUES ('" + jTextField1.getText() + "','" + jTextField5.getText() + "','" + df.format(jSpinner2.getValue()) + "/" + df.format(jSpinner1.getValue()) + "/" + df2.format(jSpinner3.getValue()) + "','" + mapersonne.getID() + "');");
}
} catch (SQLException e) {
            System.out.println(e.getMessage());
        }
Films window = new Films();
window.setVisible(true);
this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Films window = new Films();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        jTextField1.setText("");
        jTextField1.requestFocus();
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jTextField5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField5MouseClicked
        jTextField5.setText("");
        jTextField5.requestFocus();
    }//GEN-LAST:event_jTextField5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ajout_ActReal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ajout_ActReal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ajout_ActReal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ajout_ActReal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ajout_ActReal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel affiche;
    private javax.swing.JButton boutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
