/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vue;

import Contrôleur.*;
import Contrôleur.TypeDeClient;
import Modele.Connexion;
import java.awt.Color;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.Arrays;

import Contrôleur.*;
import static Contrôleur.Utilitaires.*;

/**
 *
 * @author Arthur, Kevin, Lucas, Amna
 */
public class Creation_Compte extends javax.swing.JFrame {

    
    private Connexion maconnexion;
    
    /**
     * Creates new form Creation_Compte
     */
    public Creation_Compte() {
        initComponents();
        
        //Init size
        this.setSize(new Dimension(900,600));
        
        // Init components
        jComboBox1.setEnabled(false);
        jLabel6.setText("");
        jLabel7.setText("");
        jLabel8.setText("");
        jLabel9.setText("");
        jLabel10.setText("");
        jLabel11.setText("");
        jLabel12.setText("");
        jPasswordField1.setText("");
        jPasswordField2.setText("");
        jButton1.requestFocus();
        
        // Connection à la dataBase
        
        try
        {
            maconnexion = new Connexion("projetpoojava", "root", "");
            
           /*
            for(ArrayList<String> row : LoginPasswordBDD)
            {
                for(String data : row)
                {
                    System.out.print(data + " ");
                }
                
                System.out.println();
            }
            
            */
        
        }
        catch(SQLException e)
        {
            System.out.println(e.getMessage());
        }
        catch(ClassNotFoundException e)
        {
            System.out.println(e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        prenom = new javax.swing.JTextField();
        nom = new javax.swing.JTextField();
        mail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        entrerMDP = new javax.swing.JTextField();
        confirmerMDP = new javax.swing.JTextField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPasswordField1 = new javax.swing.JPasswordField();
        oeil = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 600));
        setSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Créer un compte");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(337, 58, 263, 44);

        prenom.setForeground(new java.awt.Color(120, 120, 120));
        prenom.setText("Entrez votre Prénom");
        prenom.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        prenom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prenomMouseClicked(evt);
            }
        });
        prenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prenomActionPerformed(evt);
            }
        });
        getContentPane().add(prenom);
        prenom.setBounds(337, 168, 266, 26);

        nom.setForeground(new java.awt.Color(120, 120, 120));
        nom.setText("Entrez votre Nom");
        nom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nomMouseClicked(evt);
            }
        });
        getContentPane().add(nom);
        nom.setBounds(337, 203, 266, 22);

        mail.setForeground(new java.awt.Color(120, 120, 120));
        mail.setText("Entrez votre adresse mail");
        mail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mailMouseClicked(evt);
            }
        });
        mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailActionPerformed(evt);
            }
        });
        getContentPane().add(mail);
        mail.setBounds(337, 238, 266, 22);

        jLabel2.setText("Prénom");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(188, 171, 41, 16);

        jLabel3.setText("Nom");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(188, 206, 27, 16);

        jLabel4.setText("Adresse mail");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(188, 241, 120, 16);

        jLabel5.setText("Mot de Passe");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(188, 276, 120, 16);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(710, 470, 49, 25);

        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(621, 206, 37, 16);

        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("jLabel6");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(621, 171, 37, 16);

        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("jLabel6");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(621, 241, 290, 16);

        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("jLabel6");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(621, 276, 37, 16);

        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("jLabel6");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(620, 410, 60, 16);

        jRadioButton1.setText("Client");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(420, 380, 55, 25);

        jRadioButton2.setText("Employé");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(420, 420, 71, 25);

        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("jLabel6");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(621, 311, 260, 16);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Veuillez sélectionner une catégorie", "Régulier", "Sénior", "Enfant" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(340, 470, 260, 22);

        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("jLabel6");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(620, 470, 37, 16);

        entrerMDP.setForeground(new java.awt.Color(120, 120, 120));
        entrerMDP.setText("Entrez votre mot de passe");
        entrerMDP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entrerMDPMouseClicked(evt);
            }
        });
        getContentPane().add(entrerMDP);
        entrerMDP.setBounds(337, 273, 266, 26);

        confirmerMDP.setForeground(new java.awt.Color(120, 120, 120));
        confirmerMDP.setText("Confirmez votre mot de passe");
        confirmerMDP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmerMDPMouseClicked(evt);
            }
        });
        getContentPane().add(confirmerMDP);
        confirmerMDP.setBounds(337, 308, 266, 26);

        jPasswordField2.setText("jPasswordField1");
        jPasswordField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField2MouseClicked(evt);
            }
        });
        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        jPasswordField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordField2KeyTyped(evt);
            }
        });
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(337, 308, 266, 26);

        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseClicked(evt);
            }
        });
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyTyped(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(337, 273, 266, 26);

        oeil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/oeil.png"))); // NOI18N
        oeil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                oeilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                oeilMouseExited(evt);
            }
        });
        getContentPane().add(oeil);
        oeil.setBounds(720, 290, 30, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailActionPerformed

    }//GEN-LAST:event_mailActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        boolean okay = true;
        if (prenom.getText().equals("") || prenom.getText().equals("Entrez votre Prénom")) {
            jLabel7.setText("!!!");
            okay = false;
        } else {
            jLabel7.setText("");
        }
        if (nom.getText().equals("") || nom.getText().equals("Entrez votre Nom")) {
            jLabel6.setText("!!!");
            okay = false;
        } else {
            jLabel6.setText("");
        }
        
        boolean test = maconnexion.loginAlreadyExist(mail.getText(), jRadioButton1.isSelected());
        if (mail.getText().equals("") || mail.getText().equals("Entrez votre adresse mail")|| test ) {
            
            if(test == true)
            {
                jLabel8.setText("Email existe deja");
            }
            else
            {
                jLabel8.setText("!!!");
            }
            
            okay=false;
        } else {
            jLabel8.setText("");
        }
        if (jPasswordField1.getPassword().length == 0) {
            jLabel9.setText("!!!");
            okay = false;
        } else {
            jLabel9.setText("");
        }
        if (jPasswordField2.getPassword().length == 0) {
            jLabel11.setText("!!!");
            okay = false;
        } else if (!Arrays.equals(jPasswordField1.getPassword(), jPasswordField2.getPassword())) {
            jLabel11.setText("Veuillez entrer le même mot de passe");
            okay = false;
        } else {
            jLabel11.setText("");
        }
        if (!jRadioButton1.isSelected() && !jRadioButton2.isSelected()) {
            jLabel10.setText("!!!");
            okay = false;
        } else {
            jLabel10.setText("");
        }
        if (jRadioButton1.isSelected() && jComboBox1.getSelectedIndex() == 0) {
            jLabel12.setText("!!!");
            okay = false;
        } else {
            jLabel12.setText("");
        }
        if (okay) {
            if (jRadioButton1.isSelected()) {
                
                // Ajout du Client dans la base de données client
                try
                {
                    maconnexion.executeUpdate("INSERT INTO clients (prenom,nom,email,password,ListFilms,ListScéance,TypeClient) VALUES ('"+ prenom.getText() +"','"+ nom.getText() +"', '"+ mail.getText() +"','"+ Utilitaires.charToString(jPasswordField2.getPassword()) +"','','','"+ (String)jComboBox1.getSelectedItem() +"'); ");

                }
                catch(SQLException e)
                {
                    System.out.println(e.getMessage());
                }
                        
                // Affichage de la prochaine fenetre Acceuil Client avec le compte tout juste créer
                Accueil_Client window = new Accueil_Client(new Client(prenom.getText(),nom.getText(),mail.getText(), Utilitaires.charToString(jPasswordField2.getPassword()),"","",(String)jComboBox1.getSelectedItem()));
                window.setVisible(true);
            } else {

                // Ajout du user dans la base de données user
                try
                {
                    maconnexion.executeUpdate("INSERT INTO users (prenom,nom,email,password) VALUES ('"+ prenom.getText() +"','"+ nom.getText() +"', '"+ mail.getText() +"','"+ Utilitaires.charToString(jPasswordField2.getPassword()) +"'); ");

                }
                catch(SQLException e)
                {
                    System.out.println(e.getMessage());
                }
                        
                // Affichage de la prochaine fenetre Acceuil Client avec le compte tout juste créer
                Accueil_Employe window = new Accueil_Employe(new Utilisateur(prenom.getText(),nom.getText(),mail.getText(), Utilitaires.charToString(jPasswordField2.getPassword())));
                window.setVisible(true);
            }
            
            this.dispose();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void prenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prenomActionPerformed

    private void prenomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prenomMouseClicked
        //prenom.setFocusable(true);
        if (prenom.getText().equals("Entrez votre Prénom")) {
            prenom.setText("");
            prenom.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_prenomMouseClicked

    private void nomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nomMouseClicked
        //nom.setFocusable(true);
        if (nom.getText().equals("Entrez votre Nom")) {
            nom.setText("");
            nom.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_nomMouseClicked

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        if (jRadioButton1.isSelected() && jRadioButton2.isSelected()) {
            jRadioButton1.setSelected(false);
        }
        jComboBox1.setEnabled(false);
        jComboBox1.setSelectedIndex(0);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        if (jRadioButton1.isSelected() && jRadioButton2.isSelected()) {
            jRadioButton2.setSelected(false);
        }
        if (!jRadioButton1.isSelected()) {
            jComboBox1.setEnabled(false);
            jComboBox1.setSelectedIndex(0);
        } else {
            jComboBox1.setEnabled(true);
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void mailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mailMouseClicked
        //mail.setFocusable(true);
        if (mail.getText().equals("Entrez votre adresse mail")) {
            mail.setText("");
            mail.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_mailMouseClicked

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        entrerMDP.setText(Arrays.toString(jPasswordField1.getPassword()));
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        confirmerMDP.setText(Arrays.toString(jPasswordField2.getPassword()));
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
        // TODO add your handling code here:        

    }//GEN-LAST:event_jPasswordField1KeyPressed

    private void jPasswordField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyTyped

    }//GEN-LAST:event_jPasswordField1KeyTyped

    private void jPasswordField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField2KeyTyped

    }//GEN-LAST:event_jPasswordField2KeyTyped

    private void jPasswordField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseClicked
        entrerMDP.setVisible(false);
    }//GEN-LAST:event_jPasswordField1MouseClicked

    private void jPasswordField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField2MouseClicked
        confirmerMDP.setVisible(false);
    }//GEN-LAST:event_jPasswordField2MouseClicked

    private void oeilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oeilMouseEntered
        entrerMDP.setText(charToString(jPasswordField1.getPassword()));
        confirmerMDP.setText(charToString(jPasswordField2.getPassword()));
        jPasswordField1.setVisible(false);
        jPasswordField2.setVisible(false);
        entrerMDP.setVisible(true);
        confirmerMDP.setVisible(true);
    }//GEN-LAST:event_oeilMouseEntered

    private void oeilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oeilMouseExited
        jPasswordField1.setVisible(true);
        jPasswordField2.setVisible(true);
        entrerMDP.setVisible(false);
        confirmerMDP.setVisible(false); 
    }//GEN-LAST:event_oeilMouseExited

    private void entrerMDPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrerMDPMouseClicked
        entrerMDP.setForeground(Color.black);
        entrerMDP.setVisible(false);
        jPasswordField1.requestFocus();
    }//GEN-LAST:event_entrerMDPMouseClicked

    private void confirmerMDPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmerMDPMouseClicked
        confirmerMDP.setForeground(Color.black);
        confirmerMDP.setVisible(false);
        jPasswordField2.requestFocus();
    }//GEN-LAST:event_confirmerMDPMouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Creation_Compte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Creation_Compte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Creation_Compte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Creation_Compte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Creation_Compte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField confirmerMDP;
    private javax.swing.JTextField entrerMDP;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField nom;
    private javax.swing.JLabel oeil;
    private javax.swing.JTextField prenom;
    // End of variables declaration//GEN-END:variables
}
