/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vue;


/*
 * 
 * Librairies importées
 */
import Contrôleur.*;
import Modele.*;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.concurrent.atomic.AtomicInteger;


/**
 *
 * @author Arthur
 */
public class Identification extends javax.swing.JFrame {

    
    /*
     * Attribut privés
     * 
     */
    
    private Connexion maconnexion;
    
    private ArrayList<ArrayList<String>> ClientsList;
    private ArrayList<ArrayList<String>> UsersList;
    
    /**
     * Creates new form Identification
     */
    public Identification() {
        initComponents();
        
        //Init size
        this.setSize(new Dimension(708,470));
       
        // Initialisation
        jLabelWarningRadioButton.setText("");
        jLabelError.setText("");
        jLabel3.setText("");
   
        jLabelWarningRadioButton.requestFocus();
        
        
        // Connection à la dataBase
        
        try
        {
            maconnexion = new Connexion("projetpoojava", "root", "");
            
            ClientsList = maconnexion.executeRequete("SELECT * FROM clients;");
            UsersList = maconnexion.executeRequete("SELECT * FROM users;");
           
            /*
            for(ArrayList<String> row : LoginPasswordBDD)
            {
                for(String data : row)
                {
                    System.out.print(data + " ");
                }
                
                System.out.println();
            }
            
            */
        
        }
        catch(SQLException e)
        {
            System.out.println(e.getMessage());
        }
        catch(ClassNotFoundException e)
        {
            System.out.println(e.getMessage());
        }
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldIdentifiant = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        radioButtonClient = new javax.swing.JRadioButton();
        radioButtonEmploye = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabelError = new javax.swing.JLabel();
        jLabelWarningRadioButton = new javax.swing.JLabel();
        jButtonOK = new javax.swing.JButton();
        jButtonCreate = new javax.swing.JButton();
        jLabelAccederDirectSite = new javax.swing.JLabel();
        jLabelCachPassword = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Turfu Cinéma");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(708, 420));
        getContentPane().setLayout(null);

        jTextFieldIdentifiant.setText("Entrez votre identifiant");
        jTextFieldIdentifiant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldIdentifiantMouseClicked(evt);
            }
        });
        jTextFieldIdentifiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdentifiantActionPerformed(evt);
            }
        });
        jTextFieldIdentifiant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldIdentifiantKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldIdentifiant);
        jTextFieldIdentifiant.setBounds(222, 192, 263, 26);

        jLabel1.setText("ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(124, 195, 20, 16);

        jLabel2.setText("Mot de Passe");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(64, 235, 80, 16);

        radioButtonClient.setText("Client");
        radioButtonClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonClientActionPerformed(evt);
            }
        });
        getContentPane().add(radioButtonClient);
        radioButtonClient.setBounds(222, 297, 55, 25);

        radioButtonEmploye.setText("Employé");
        radioButtonEmploye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonEmployeActionPerformed(evt);
            }
        });
        getContentPane().add(radioButtonEmploye);
        radioButtonEmploye.setBounds(333, 297, 71, 25);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("MY POPCORN");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(222, 89, 240, 44);

        jLabelError.setForeground(new java.awt.Color(255, 0, 0));
        jLabelError.setText("jLabel6"); // NOI18N
        getContentPane().add(jLabelError);
        jLabelError.setBounds(500, 190, 140, 40);

        jLabelWarningRadioButton.setForeground(new java.awt.Color(255, 0, 0));
        jLabelWarningRadioButton.setText("jLabel8");
        getContentPane().add(jLabelWarningRadioButton);
        jLabelWarningRadioButton.setBounds(420, 280, 230, 60);

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOK);
        jButtonOK.setBounds(540, 365, 49, 25);

        jButtonCreate.setText("Créer un compte");
        jButtonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCreate);
        jButtonCreate.setBounds(12, 365, 121, 25);

        jLabelAccederDirectSite.setForeground(new java.awt.Color(51, 153, 255));
        jLabelAccederDirectSite.setText("Acceder directement au site sans compte ....   -->");
        jLabelAccederDirectSite.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255), 2));
        jLabelAccederDirectSite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAccederDirectSiteMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelAccederDirectSite);
        jLabelAccederDirectSite.setBounds(222, 365, 261, 20);

        jLabelCachPassword.setText("Entrez votre mot de passe");
        jLabelCachPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCachPasswordMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelCachPassword);
        jLabelCachPassword.setBounds(228, 232, 263, 26);

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(222, 232, 263, 26);

        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(500, 220, 130, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIdentifiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdentifiantActionPerformed

        
    }//GEN-LAST:event_jTextFieldIdentifiantActionPerformed

    private void radioButtonClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonClientActionPerformed
        
        if((radioButtonEmploye.isSelected() == true)||(radioButtonClient.isSelected() == false))
        {
            radioButtonEmploye.setSelected(!radioButtonEmploye.isSelected());
        }
        
        if (!jLabelWarningRadioButton.getText().equals(""))
        {
            jLabelWarningRadioButton.setText("");
        }
        
        
    }//GEN-LAST:event_radioButtonClientActionPerformed

    private void radioButtonEmployeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonEmployeActionPerformed
       
         if((radioButtonEmploye.isSelected() == false)||(radioButtonClient.isSelected() == true))
        {
        radioButtonClient.setSelected(!radioButtonClient.isSelected());
        }
         
         
         if (!jLabelWarningRadioButton.getText().equals(""))
        {
            jLabelWarningRadioButton.setText("");
        }
         
    }//GEN-LAST:event_radioButtonEmployeActionPerformed

    private void jButtonCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateActionPerformed
       
        Creation_Compte theWindow = new Creation_Compte();
                    
        theWindow.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_jButtonCreateActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        
        String bufferString = "";
        AtomicInteger bufferIndex = new AtomicInteger(0);
        
        if(checkConditions(true))
        {
            //Test si le login existe dans sa bonne base de donnée:
            bufferString = TestLoginExist(bufferIndex);
            
            if(!bufferString.equals(""))
            {
                if(bufferString.equals(Utilitaires.charToString(jPasswordField1.getPassword())))
                {
                    //System.out.println("All good");
                    
                   
                    if(radioButtonEmploye.isSelected())
                    {   
                        // Affichage de la fenetre Accueil Employé avec le comte de d'employé 
                         // Affichage de la prochaine fenetre Acceuil Client avec le compte tout juste créer
                        Accueil_Employe window = new Accueil_Employe(new Utilisateur(UsersList.get(bufferIndex.get()).get(0),UsersList.get(bufferIndex.get()).get(1),UsersList.get(bufferIndex.get()).get(2),UsersList.get(bufferIndex.get()).get(3)));
                        window.setVisible(true);
                        this.dispose();
                    }
                    else
                    {
                         // Affichage de la fenetre Accueil Client avec le comte du client 
                        Accueil_Client window = new Accueil_Client(new Client(ClientsList.get(bufferIndex.get()).get(0),ClientsList.get(bufferIndex.get()).get(1),ClientsList.get(bufferIndex.get()).get(2),ClientsList.get(bufferIndex.get()).get(3),ClientsList.get(bufferIndex.get()).get(4),ClientsList.get(bufferIndex.get()).get(5),ClientsList.get(bufferIndex.get()).get(6)));
                   
                        window.setVisible(true);
                       this.dispose();
                       
                    }
                     
                }
                else
                {
                   jLabelError.setText("ID or Password or ");
                   jLabel3.setText("\"Type\" incorrect");
                }
            }
            else
            {
                 jLabelError.setText("ID or Password or ");
                 jLabel3.setText("\"Type\" incorrect");
            }
        }
        else
        {
             //Test si le login existe dans sa bonne base de donnée:
            bufferString = TestLoginExist(bufferIndex);
            
            if(!bufferString.equals(""))
            {
                if(bufferString.equals(Utilitaires.charToString(jPasswordField1.getPassword())))
                {
                    //nothing
                }
                else
                {
                    jLabelError.setText("ID or Password or ");
                    jLabel3.setText("\"Type\" incorrect");
                }
            }
            else
            {
                 jLabelError.setText("ID or Password or ");
                 jLabel3.setText("\"Type\" incorrect");
            }
        }
        
        
        
    }//GEN-LAST:event_jButtonOKActionPerformed

    //Test si le login exist dans sa bonne base de données : soit users, soit Clients
    private String TestLoginExist(AtomicInteger bufferIndex)
    {
        String result = "";
        int compt = 0;
        
        if(radioButtonEmploye.isSelected())
        {
            for(ArrayList<String> row : UsersList)
            {
                if(row.get(2).equals(jTextFieldIdentifiant.getText().trim()))
                {
                    result = row.get(3);
                    bufferIndex.set(compt);
                   
                    break;
                }
                
                compt++;
            }
            
        }
        else
        {
            
            for(ArrayList<String> row : ClientsList)
            {
                if(row.get(2).equals(jTextFieldIdentifiant.getText()))
                {
                    result = row.get(3);
                    bufferIndex.set(compt);
                    break;
                }
                
                compt++;
            }
            
        }
        
        return result;
    }
    
    private void jTextFieldIdentifiantKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIdentifiantKeyPressed

     if (!jLabelError.getText().equals(""))
        {
            jLabelError.setText("");
            jLabel3.setText("");
        }
    
    }//GEN-LAST:event_jTextFieldIdentifiantKeyPressed

    private void jTextFieldIdentifiantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldIdentifiantMouseClicked
        
        if ("Entrez votre identifiant".equals(jTextFieldIdentifiant.getText()))
        {
            jTextFieldIdentifiant.setText("");
        }
        
    }//GEN-LAST:event_jTextFieldIdentifiantMouseClicked

    private void jLabelAccederDirectSiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAccederDirectSiteMouseClicked

        Accueil_Client window = new Accueil_Client(new Client());
        window.setVisible(true);
      
        this.dispose();
        
    }//GEN-LAST:event_jLabelAccederDirectSiteMouseClicked

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jLabelCachPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCachPasswordMouseClicked
        jLabelCachPassword.setVisible(false);
        jPasswordField1.requestFocus();
    }//GEN-LAST:event_jLabelCachPasswordMouseClicked

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed

        
        if (! jLabelError.getText().equals(""))
        {
           jLabelError.setText("");
           jLabel3.setText("");
        }
        
    }//GEN-LAST:event_jPasswordField1KeyPressed

    
    private boolean checkConditions(boolean Printing)
    { 
        boolean good = true;
        
        jLabelError.setText("");
        jLabel3.setText("");
        
        if((radioButtonEmploye.isSelected() == false)&&(radioButtonClient.isSelected() == false))
        {
            if (Printing == true)
                jLabelWarningRadioButton.setText("Selectionner une des deux catégories!!!");
            good = false;
        }
        else
        {
            jLabelWarningRadioButton.setText("");
        }
        
        if(("".equals(jTextFieldIdentifiant.getText()))||("Entrez votre identifiant".equals(jTextFieldIdentifiant.getText())))
        {
            if (Printing == true)
            {
                jLabelError.setText("'''");
            }
            
             good = false;
             
        }
        else
        {
            jLabelError.setText("");
        }
        
        if("".equals(Utilitaires.charToString(jPasswordField1.getPassword())))
        {
            if (Printing == true)
            {
                jLabelError.setText("'''");
            }
             good = false;
        }
        else
        {
            jLabelError.setText("");
        }
        
        
        
       return  good;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Identification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Identification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Identification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Identification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Identification().setVisible(true);
            }
        });
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCreate;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelAccederDirectSite;
    private javax.swing.JLabel jLabelCachPassword;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelWarningRadioButton;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextFieldIdentifiant;
    private javax.swing.JRadioButton radioButtonClient;
    private javax.swing.JRadioButton radioButtonEmploye;
    // End of variables declaration//GEN-END:variables
}
