/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import java.awt.Dimension;

/**
 *
 * @author Amna9
 */
public class Offres extends javax.swing.JFrame {

    /**
     * Creates new form Offres
     */
    public Offres() {
        initComponents();
         //Init size
        this.setSize(new Dimension(900, 700));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        Accueil = new javax.swing.JButton();
        Films = new javax.swing.JButton();
        Dossiers = new javax.swing.JButton();
        Offres = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 51, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel1.setText("Offres");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 119, 53);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("OFFRES ACTUELLES");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 90, 250, 30);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Régulier : -20%", "Sénior : -40%", "Junior : -60%" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 140, 630, 178);

        Accueil.setBackground(new java.awt.Color(253, 0, 0));
        Accueil.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        Accueil.setText("Accueil");
        Accueil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccueilMouseClicked(evt);
            }
        });
        Accueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccueilActionPerformed(evt);
            }
        });
        getContentPane().add(Accueil);
        Accueil.setBounds(10, 580, 154, 41);

        Films.setBackground(new java.awt.Color(253, 0, 0));
        Films.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        Films.setText("Films");
        Films.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilmsActionPerformed(evt);
            }
        });
        getContentPane().add(Films);
        Films.setBounds(170, 580, 154, 41);

        Dossiers.setBackground(new java.awt.Color(253, 0, 0));
        Dossiers.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        Dossiers.setText("Acteurs");
        Dossiers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DossiersActionPerformed(evt);
            }
        });
        getContentPane().add(Dossiers);
        Dossiers.setBounds(340, 580, 154, 41);

        Offres.setBackground(new java.awt.Color(253, 0, 0));
        Offres.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        Offres.setText("Offres");
        Offres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OffresActionPerformed(evt);
            }
        });
        getContentPane().add(Offres);
        Offres.setBounds(500, 580, 154, 40);

        jButton2.setText("Se déconnecter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(540, 0, 139, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AccueilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccueilMouseClicked

    }//GEN-LAST:event_AccueilMouseClicked

    private void AccueilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccueilActionPerformed
        Accueil_Employe g = new Accueil_Employe();
        g.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AccueilActionPerformed

    private void FilmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilmsActionPerformed
        Films g = new Films();
        g.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_FilmsActionPerformed

    private void DossiersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DossiersActionPerformed
        Films g = new Films();
        g.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_DossiersActionPerformed

    private void OffresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OffresActionPerformed
        Offres g = new Offres();
        g.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_OffresActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Identification window = new Identification();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Offres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Offres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Offres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Offres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Offres().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Accueil;
    private javax.swing.JButton Dossiers;
    private javax.swing.JButton Films;
    private javax.swing.JButton Offres;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
