/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vue;

import Contrôleur.Client;
import Contrôleur.Film;
import Contrôleur.Personne;
import Modele.Connexion;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.*;

/**
 * Affiche le profil du client
 * @author Arthur, Kevin, Lucas, Amna
 */
public class Profil extends javax.swing.JFrame {

    private Client User;
    private String BuffMail;

    private Connexion maconnexion;

    /**
     * Creates new form Profil
     */
    public Profil(Client theUser) {
        initComponents();
        jPanel1.hide();
        jButtonAnnule.setVisible(false);

        User = new Client(theUser);
        BuffMail = User.getEmail();

        jLabelPrenomNom.setText("Name : " + User.getPrenom() + " " + User.getNom());
        jLabelMail.setText("Mail : " + User.getEmail());

        try {
            maconnexion = new Connexion("projetpoojava", "root", "");

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } catch (ClassNotFoundException e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelPrenomNom = new javax.swing.JLabel();
        jLabelMail = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButtonAnnule = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 600));
        setSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("Mon Profil");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 620, 73);

        jButton6.setText("Voir les films");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(0, 120, 225, 29);

        jButton1.setText("Voir les acteurs");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(220, 120, 225, 29);

        jButton2.setText("Accueil");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(660, 120, 225, 29);

        jButton3.setText("Voir les réalisateurs");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(440, 120, 225, 29);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profil.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 190, 200, 200);

        jLabelPrenomNom.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelPrenomNom.setText("Prénom Nom");
        getContentPane().add(jLabelPrenomNom);
        jLabelPrenomNom.setBounds(300, 200, 620, 50);

        jLabelMail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelMail.setText("mail");
        getContentPane().add(jLabelMail);
        jLabelMail.setBounds(300, 270, 620, 40);

        jButton7.setText("Modifier la photo");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(20, 390, 200, 29);

        jButton8.setText("Modifier");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(20, 460, 200, 29);

        jButtonAnnule.setText("Annuler");
        jButtonAnnule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnuleActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAnnule);
        jButtonAnnule.setBounds(20, 500, 200, 29);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mon compte", "Voir mon profil", "Mes films ", "Prochaines séances", "Se déconnecter" }));
        jComboBox1.setSelectedIndex(1);
        jComboBox1.setToolTipText("");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(660, 50, 220, 26);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField4.setText("mot de passe");
        jPanel1.add(jTextField4);
        jTextField4.setBounds(20, 140, 620, 40);

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField3.setText("mail");
        jPanel1.add(jTextField3);
        jTextField3.setBounds(20, 80, 620, 40);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField1.setText("jTextField1");
        jPanel1.add(jTextField1);
        jTextField1.setBounds(20, 10, 300, 50);

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField2.setText("jTextField1");
        jPanel1.add(jTextField2);
        jTextField2.setBounds(340, 10, 310, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(230, 190, 650, 200);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        TousLesFilms filo = new TousLesFilms(2, User);
        filo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Accueil_Client window = new Accueil_Client(User);
        window.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (jButton8.getText().equals("Modifier")) {

            jPanel1.show();

            jLabelPrenomNom.setVisible(false);
            jLabelMail.setVisible(false);

            jButton8.setText("Sauvegarder");
            jButtonAnnule.setVisible(true);

            jTextField1.setText(User.getPrenom());
            jTextField2.setText(User.getNom());
            jTextField3.setText(User.getEmail());
            jTextField4.setText(User.getPassword());

        } else {
            User.setPrenom(jTextField1.getText());
            User.setNom(jTextField2.getText());
            BuffMail = User.getEmail();
            User.setEmail(jTextField3.getText());
            User.setPassword(jTextField4.getText());

            jLabelPrenomNom.setText("Name : " + User.getPrenom() + " " + User.getNom());
            jLabelMail.setText("Mail : " + User.getEmail());

            jPanel1.hide();
            jLabelPrenomNom.setVisible(true);
            jLabelMail.setVisible(true);

            jButton8.setText("Modifier");
            jButtonAnnule.setVisible(false);

            // Envoie des modifications à la BDD
            try {
                maconnexion.executeUpdate("UPDATE clients SET prenom = '"+User.getPrenom()+"', nom='"+User.getNom()+"', email = '"+User.getEmail()+"', password = '"+User.getPassword()+"'  WHERE  email = '"+BuffMail+"';");

            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }

        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButtonAnnuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnuleActionPerformed

        jPanel1.hide();
        jLabelPrenomNom.setVisible(true);
        jLabelMail.setVisible(true);

        jButton8.setText("Modifier");
        jButtonAnnule.setVisible(false);
    }//GEN-LAST:event_jButtonAnnuleActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        jLabel2.setIcon(new ImageIcon(chooser.getSelectedFile().toString()));
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if (jComboBox1.getSelectedIndex() != 0) {
            switch (jComboBox1.getSelectedIndex()) {
                case 1: // voir mon profil
                    Profil window = new Profil(User);
                    window.setVisible(true);
                    this.dispose();
                    break;
                case 2: // voir mes films
                    VoirMesFilms window2 = new VoirMesFilms(User);
                    window2.setVisible(true);
                    this.dispose();
                    break;
                case 3: // voir mes scéances
                    //  MesSeances window3 = new MesSeances();
                    //  window3.setVisible(true);
                    // this.dispose();
                    break;

                case 4: // deconnexion

                    Identification theWindow3 = new Identification();
                    theWindow3.setVisible(true);

                    this.dispose();
                    break;

                default:
                    break;
            }
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TousLesFilms filo = new TousLesFilms(1, User);
        filo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        TousLesFilms filo = new TousLesFilms(2, User);
        filo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profil(new Client()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButtonAnnule;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelMail;
    private javax.swing.JLabel jLabelPrenomNom;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
