/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vue;

import Modele.Connexion;
import java.awt.Dimension;
import static java.lang.Math.abs;
import java.sql.SQLException;
import java.util.*;
import javax.swing.*;
import Contrôleur.*;
import java.io.File;
import java.io.FileNotFoundException;

/**
 *
 * @author Arthur
 */
public class VoirMesFilms extends javax.swing.JFrame {

    private Connexion maconnexion;

    private ArrayList<Film> FilmList;
    
    private Client User;

    /**
     * Creates new form TousLesFilms
     */
    public VoirMesFilms() {
        initComponents();

        //Init size
        this.setSize(new Dimension(900, 700));

        // Init buffer list of film
        ArrayList<ArrayList<String>> ListBuffer = null;

        // Init the real list of film
        FilmList = new ArrayList<Film>();

        // Chargement de tout les films présent dans la base de données
        try {
            maconnexion = new Connexion("projetpoojava", "root", "");

            ListBuffer = maconnexion.executeRequete("SELECT * FROM films;");

            // Creation de la liste d'objet de type films
            for (ArrayList<String> row : ListBuffer) {

                FilmList.add(new Film(row, maconnexion));
            }

           

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } catch (ClassNotFoundException e) {
            System.out.println(e.getMessage());
        }

        

        //Première initialisation
        initPanelApresRequete();

       
        // Init User 
        User = new Client();

    }

    public VoirMesFilms(Client theUser) {
        initComponents();

        //Init size
        this.setSize(new Dimension(900, 700));

        // Init buffer list of film
        ArrayList<ArrayList<String>> ListBuffer = null;

        // Init the real list of film
        FilmList = new ArrayList<Film>();



        // Chargement de tout les films présent dans la base de données
        try {
            maconnexion = new Connexion("projetpoojava", "root", "");

            ListBuffer = maconnexion.executeRequete("SELECT ListFilms FROM clients WHERE email= '" + theUser.getEmail() + "';");

            
            String Buffer = ListBuffer.get(0).get(0);
              
                if (Buffer != "") {
                   String [] Buffer2 = Buffer.split(",");
                    

                    for (String IDfilm : Buffer2) {
                        
                      ArrayList<ArrayList<String>>  ListBuffer2 = maconnexion.executeRequete("SELECT * FROM films WHERE IDfilm= '" + IDfilm + "';");

                      FilmList.add(new Film(ListBuffer2.get(0), maconnexion));
                        
                    }
                }


        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } catch (ClassNotFoundException e) {
            System.out.println(e.getMessage());
        }
        //Première initialisation
        initPanelApresRequete();
        
        // Init User 
        User = new Client(theUser);
        
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanelUpperPart = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabelGrosTitre = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabelNumberResult = new javax.swing.JLabel();
        jPanelLowerPart = new javax.swing.JPanel();
        jPanelFilm1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanelFilm2 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(null);

        jScrollBar1.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                jScrollBar1AdjustmentValueChanged(evt);
            }
        });
        getContentPane().add(jScrollBar1);
        jScrollBar1.setBounds(850, 340, 17, 290);

        jPanelUpperPart.setLayout(null);

        jButton4.setText("Voir les films");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanelUpperPart.add(jButton4);
        jButton4.setBounds(0, 90, 225, 25);

        jButton1.setText("Voir les acteurs");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelUpperPart.add(jButton1);
        jButton1.setBounds(220, 90, 225, 25);

        jButton3.setText("Voir les réalisateurs");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanelUpperPart.add(jButton3);
        jButton3.setBounds(440, 90, 225, 25);

        jButton2.setText("Accueil");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanelUpperPart.add(jButton2);
        jButton2.setBounds(660, 90, 225, 25);

        jLabelGrosTitre.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelGrosTitre.setText("Mes Films Favoris");
        jPanelUpperPart.add(jLabelGrosTitre);
        jLabelGrosTitre.setBounds(220, 150, 620, 73);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mon compte", "Voir mon profil", "Mes films ", "Prochaines séances", "Se déconnecter" }));
        jComboBox1.setToolTipText("");
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanelUpperPart.add(jComboBox1);
        jComboBox1.setBounds(660, 40, 220, 22);

        jLabel19.setText("Nombre de favoris : ");
        jPanelUpperPart.add(jLabel19);
        jLabel19.setBounds(40, 300, 130, 16);

        jLabelNumberResult.setForeground(new java.awt.Color(255, 51, 51));
        jLabelNumberResult.setText("Number");
        jPanelUpperPart.add(jLabelNumberResult);
        jLabelNumberResult.setBounds(160, 300, 170, 16);

        getContentPane().add(jPanelUpperPart);
        jPanelUpperPart.setBounds(0, 10, 890, 320);
        getContentPane().add(jPanelLowerPart);
        jPanelLowerPart.setBounds(0, 630, 850, 60);

        jPanelFilm1.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFilm1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelFilm1MouseClicked(evt);
            }
        });
        jPanelFilm1.setLayout(null);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel21.setText("Titre du film");
        jPanelFilm1.add(jLabel21);
        jLabel21.setBounds(310, 10, 490, 40);

        jLabel22.setText("Affiche du film");
        jLabel22.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelFilm1.add(jLabel22);
        jLabel22.setBounds(50, 20, 200, 260);

        jLabel1.setText("Avec : acteur1, acteur 2, acteur 3");
        jPanelFilm1.add(jLabel1);
        jLabel1.setBounds(280, 110, 530, 40);

        jLabel2.setText("De : Realisateur");
        jPanelFilm1.add(jLabel2);
        jLabel2.setBounds(280, 90, 480, 20);

        jLabel3.setText("Date/ Durée / Genre");
        jPanelFilm1.add(jLabel3);
        jLabel3.setBounds(280, 60, 530, 16);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel17.setText("Note : truc/5");
        jPanelFilm1.add(jLabel17);
        jLabel17.setBounds(650, 230, 200, 30);

        jLabel18.setText("Pays : ");
        jPanelFilm1.add(jLabel18);
        jLabel18.setBounds(280, 150, 300, 16);

        jLabel23.setForeground(new java.awt.Color(51, 255, 255));
        jLabel23.setText("Clique pour le détail et réserver !!");
        jPanelFilm1.add(jLabel23);
        jLabel23.setBounds(350, 260, 190, 16);

        getContentPane().add(jPanelFilm1);
        jPanelFilm1.setBounds(10, 340, 830, 290);

        jPanelFilm2.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFilm2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelFilm2MouseClicked(evt);
            }
        });
        jPanelFilm2.setLayout(null);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel24.setText("Titre du film");
        jPanelFilm2.add(jLabel24);
        jLabel24.setBounds(310, 10, 490, 40);

        jLabel25.setText("Affiche du film");
        jLabel25.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelFilm2.add(jLabel25);
        jLabel25.setBounds(50, 20, 200, 260);

        jLabel26.setText("Avec : acteur1, acteur 2, acteur 3");
        jPanelFilm2.add(jLabel26);
        jLabel26.setBounds(280, 110, 530, 40);

        jLabel27.setText("De : Realisateur");
        jPanelFilm2.add(jLabel27);
        jLabel27.setBounds(280, 90, 480, 20);

        jLabel28.setText("Date/ Durée / Genre");
        jPanelFilm2.add(jLabel28);
        jLabel28.setBounds(280, 60, 530, 16);

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel29.setText("Note : truc/5");
        jPanelFilm2.add(jLabel29);
        jLabel29.setBounds(650, 230, 200, 30);

        jLabel30.setText("Pays : ");
        jPanelFilm2.add(jLabel30);
        jLabel30.setBounds(280, 150, 300, 16);

        jLabel31.setForeground(new java.awt.Color(51, 255, 255));
        jLabel31.setText("Clique pour le détail et réserver !!");
        jPanelFilm2.add(jLabel31);
        jLabel31.setBounds(350, 260, 190, 16);

        getContentPane().add(jPanelFilm2);
        jPanelFilm2.setBounds(10, 340, 830, 290);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(420, 490, 0, 2);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(10, 630, 830, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       TousLesFilms filo = new  TousLesFilms(0,User);
        filo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Accueil_Client window = new Accueil_Client(User);
        window.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jScrollBar1AdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_jScrollBar1AdjustmentValueChanged

        int valueScroll = jScrollBar1.getValue();

        int spacePerPannel = jPanelFilm1.getHeight() + 20;
        int restScroll = valueScroll % spacePerPannel;
        int NumberPannelPassed = (valueScroll - restScroll) / spacePerPannel;

        int Base = 340 + (NumberPannelPassed) * spacePerPannel;

        // Changement de position des pannels en fonction du slider 
        jPanelFilm1.setLocation(10, Base - valueScroll);
        jPanelFilm2.setLocation(10, Base - valueScroll + spacePerPannel);


            /// Remplissage des pannels avec les bons films dedans
            // Remplisage premier panel déroulant
            FilmList.get(NumberPannelPassed).remplirPannelFilm(jLabel21, jLabel22, jLabel3, jLabel2, jLabel1, jLabel17, jLabel18, jLabel23);

            // Si l'on n'est pas deja arriver au dernier film de la list avec le premier pannel
            if (NumberPannelPassed != (FilmList.size() - 1)) {
                // Remplisage deuxième panel déroulant
                FilmList.get(NumberPannelPassed + 1).remplirPannelFilm(jLabel24, jLabel25, jLabel28, jLabel27, jLabel26, jLabel29, jLabel30, jLabel31);

            }

        

    }//GEN-LAST:event_jScrollBar1AdjustmentValueChanged

    private void jPanelFilm1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelFilm1MouseClicked
        
        int valueScroll = jScrollBar1.getValue();

        int spacePerPannel = jPanelFilm1.getHeight() + 20;
        int restScroll = valueScroll % spacePerPannel;
        int NumberPannelPassed = (valueScroll - restScroll) / spacePerPannel;

        int Base = 340 + (NumberPannelPassed) * spacePerPannel;
        

            Film_Infos infos = new Film_Infos(FilmList.get(NumberPannelPassed),User);
            infos.setVisible(true);
            this.dispose();

        
    }//GEN-LAST:event_jPanelFilm1MouseClicked

    private void jPanelFilm2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelFilm2MouseClicked
      
        int valueScroll = jScrollBar1.getValue();

        int spacePerPannel = jPanelFilm1.getHeight() + 20;
        int restScroll = valueScroll % spacePerPannel;
        int NumberPannelPassed = (valueScroll - restScroll) / spacePerPannel;

        int Base = 340 + (NumberPannelPassed) * spacePerPannel;
        
 
            Film_Infos infos = new Film_Infos(FilmList.get(NumberPannelPassed+1),User);
            infos.setVisible(true);
            this.dispose();
 
    }//GEN-LAST:event_jPanelFilm2MouseClicked

   

    private void initPanelApresRequete() {
        // Initialization des position des panels après une requete SQL
        int heightPannels = jPanelFilm1.getHeight();
        int theSize = 0;
       
            theSize = FilmList.size();


        //Initialise la position de depart des panels
        jPanelFilm1.setLocation(10, 340);
        jPanelFilm2.setLocation(10, 340 + 20 + heightPannels);

        // Init le nombre de résultat trouver
        jLabelNumberResult.setText(Integer.toString(theSize));

        if (theSize == 0) {
            jPanelFilm1.hide();
            jPanelFilm2.hide();

            jScrollBar1.hide();

        } else {
            jPanelFilm1.show();
            jPanelFilm2.show();

            jScrollBar1.show();

            if (theSize == 1) {
                jScrollBar1.hide();

               
                    FilmList.get(0).remplirPannelFilm(jLabel21, jLabel22, jLabel3, jLabel2, jLabel1, jLabel17, jLabel18, jLabel23);

            }

            // Init value slider
            jScrollBar1.setValue(0);

            // Calcul taille nécessaire du slider en fonction du nombre d'éléments
            jScrollBar1.setMaximum((theSize - 1) * jPanelFilm1.getHeight() + (theSize - 2) * 20 + 30);

        }

    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       TousLesFilms filo = new  TousLesFilms(1,User);
        filo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        TousLesFilms filo = new  TousLesFilms(2,User);
        filo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
       
     if (jComboBox1.getSelectedIndex() != 0) {
            switch (jComboBox1.getSelectedIndex()) {
                case 1: // voir mon profil
                    Profil window = new Profil(User);
                    window.setVisible(true);
                    this.dispose();
                    break;
                case 2: // voir mes films
                    MesFilms window2 = new MesFilms();
                    window2.setVisible(true);
                    this.dispose();
                    break;
                case 3: // voir mes scéances
                    MesSeances window3 = new MesSeances();
                    window3.setVisible(true);
                    this.dispose();
                    break;
                    
                case 4: // deconnexion
                    
                    Identification theWindow3 = new Identification();
                    theWindow3.setVisible(true);

                    this.dispose();
                    break;
                    
                default:
                    break;
            }
        }
        
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
         if ((User.getPrenom() == "NoAccountUser") && (User.getNom() == "") && (User.getEmail() == "noMail") && (User.getPassword() == "noPassword")) {
            Identification theWindow3 = new Identification();
            theWindow3.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jComboBox1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VoirMesFilms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VoirMesFilms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VoirMesFilms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VoirMesFilms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VoirMesFilms().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabelGrosTitre;
    private javax.swing.JLabel jLabelNumberResult;
    private javax.swing.JPanel jPanelFilm1;
    private javax.swing.JPanel jPanelFilm2;
    private javax.swing.JPanel jPanelLowerPart;
    private javax.swing.JPanel jPanelUpperPart;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
